[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cc-detector"
version = "0.0.0"
description = "Credit card detection helper"
authors = [ {name = "bytechie"} ]

[tool.pytest]
addopts = ["-q"]
